"""Add answer column to Submission table

Revision ID: b7d6d481f036
Revises: c2e60d01e7b7
Create Date: 2024-12-19 04:08:55.942746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7d6d481f036'
down_revision = 'c2e60d01e7b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('answer', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_column('answer')

    # ### end Alembic commands ###
