"""add status column in table role

Revision ID: c2e60d01e7b7
Revises: c4ac520d91da
Create Date: 2024-12-08 13:50:15.229451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2e60d01e7b7'
down_revision = 'c4ac520d91da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('active', 'inactive', 'pending', name='rolestatusenum'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
