from models.user import UserModel
from models.disabled_user import DisabledUserModel
from models.institute import InstituteModel
from models.role import RoleModel
from models.course import CourseModel
from models.module import ModuleModel
from models.assessment import AssessmentModel
from models.assessment_detail import AssessmentDetailModel
from models.enrollment import EnrollmentModel
from models.submission import SubmissionModel
